---
- name: updates | configure apt
  template:
    src: templates/91-ansible-apt.j2
    dest: /etc/apt/apt.conf.d/91-ansible-apt
  
- name: updates | configure unattended-upgrades
  template:
    src: templates/92-unattended.j2
    dest: /etc/apt/apt.conf.d/92-unattended