---
- hosts: "all"
  become: true
  tasks:
  - name: "clone git repo"
    git:
      repo: 'https://{{ username | urlencode }}:{{ password | urlencode }}@gitlab.coolclever.tech/devops/provisioning/services/{{ app }}.git'
      dest: /home/ansible/services/{{ app }}
    vars:
      username: cicdiser
      password: 
      app: node-exporter

  - name: "Login to DockerHub"
    command: "docker login gitlab.coolclever.tech:5005 -u {{ docker_username }} -p {{ docker_password }}"
    vars:
      docker_username: cicdiser
      docker_password: 
