---
- hosts: "all"
  become: true
  vars:
      username: cicdiser
      password: 
      appdir: /home/ansible/services
      app: node-exporter
  tasks:
  - name: "clone git repo"
    git:
      repo: 'https://{{ username | urlencode }}:{{ password | urlencode }}@gitlab.coolclever.tech/devops/provisioning/services/{{ app }}.git'
      dest: "{{ appdir }}/{{ app }}"
  - name: "Login to DockerHub"
    command: "docker login gitlab.coolclever.tech:5005 -u {{ username }} -p {{ password }}"

  - name: "run docker compose"
    ansible.builtin.command: docker compose -f {{ appdir }}/{{ app }}/docker-compose.yaml up -d
